CREATE TABLE uzytkownicy (
    nazwa_uzytkownika VARCHAR2(50) PRIMARY KEY,
    haslo VARCHAR2(100),
    wlaczony Character(1),
    imie VARCHAR2(50),
    nazwisko VARCHAR2(50),
    data_urodzenia DATE
);

CREATE TABLE uprawnienia (
    nazwa_uzytkownika VARCHAR2(50),
    uprawnienie VARCHAR2(50),
    CONSTRAINT fk_uprawnienia_uzytkownicy FOREIGN KEY (nazwa_uzytkownika) REFERENCES uzytkownicy(nazwa_uzytkownika)
);
INSERT INTO uzytkownicy (nazwa_uzytkownika, haslo, wlaczony)
VALUES ('user', '$2a$10$yByFdDgLOM9JhAcv4EyhJOsciXf4U.ugvI1XfYwUNWsolizh0CAgm','T');
INSERT INTO uprawnienia (nazwa_uzytkownika, uprawnienie)
VALUES ('user', 'USER');
INSERT INTO uzytkownicy (nazwa_uzytkownika, haslo, wlaczony)
VALUES ('admin', '$2a$10$oJFe92XqWcKO2u0emnEFXOeRP.QUiTo0NIhyYs7hFI6sEMY81b1r6','T');
INSERT INTO uprawnienia (nazwa_uzytkownika, uprawnienie)
VALUES ('admin', 'ADMIN');

ALTER TABLE Uprawnienia
    ADD id_uprawnienia Integer GENERATED BY DEFAULT ON NULL AS IDENTITY;

CREATE SEQUENCE Sequence_id_uprawnienia
    INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
 NOMINVALUE
 CACHE 20
/

ALTER TABLE uzytkownicy
    ADD plec VARCHAR2(10); -- Określ odpowiedni typ danych i rozmiar dla kolumny "plec"

ALTER TABLE uzytkownicy
    ADD adres_email VARCHAR2(255); -- Określ odpowiedni typ danych i rozmiar dla kolumny "adres_email"

ALTER TABLE uzytkownicy
    ADD telefon VARCHAR2(20); -- Określ odpowiedni typ danych i rozmiar dla kolumny "telefon"
